src/app/urls.py
from os import name
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

from core import views

from admin import view_admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', views.HomeView.as_view(), name='home'),
    path('contact/',views.ContactView.as_view(), name='contact'),
    path('nosotros/',views.NosotrosView.as_view(), name='nosotros'),
    path('cart/', include('cart.urls', namespace='cart')),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    
    path('adminprincipal/', view_admin.adminprincipal, name='admin'),
    path('admin_ver_productos/', view_admin.Admin_ver_productos.as_view(), 
         name='admin_ver_productos'),
    path('admin_añadir_productos/', view_admin.Admin_Agregar_productos.as_view(), 
         name='admin_agregar_productos'),
    path('admin_actualizar_productos/<int:pk>/', view_admin.Actualizar_producto.as_view(),
         name='admin_actualizar_productos'),
    path('admin_eliminar_productos/<int:pk>/', view_admin.Eliminar_producto.as_view(),
         name='admin_eliminar_productos'),
    path('admin_ver_proveedores/', view_admin.Admin_ver_proveedores.as_view(), 
        name='admin_ver_proovedores'),
    path('admin_añadir_proveedores/', view_admin.Admin_Agregar_proveedores.as_view(), 
        name='admin_agregar_proovedores'),
    path('admin_actualizar_proovedores/<int:pk>/', view_admin.Actualizar_proveedores.as_view(),
         name='admin_actualizar_proovedores'),
    path('admin_ver_ventas/', view_admin.Admin_ver_ordenes, 
         name='admin_ver_ventas'),
    path('admin_ver_pagos/', view_admin.Admin_ver_pagos.as_view(), 
         name='admin_ver_pagos'),
    path('admin_ver_usuarios/', view_admin.Admin_ver_usuarios, 
         name='admin_ver_usuarios'),
    path('admin_registrar_usuarios/', view_admin.administrador_signup_view , 
         name='admin_registrar_usuarios'),
    path('admin_actualizar_administradores/<int:pk>', view_admin.admin_acutalizar_administradores,
         name='admin_actualizar_administradores'),
     path('admin_ver_categorias/', view_admin.Admin_ver_categorias.as_view(), name='admin_ver_categorias'),
     path('admin_añadir_categorias/', view_admin.Admin_Agregar_categorias.as_view(), name='admin_agregar_categorias'),
     path('admin_actualizar_categorias/<int:pk>/', view_admin.Actualizar_categoria.as_view(),
     name='admin_actualizar_categorias'),
     path('admin_eliminar_categorias/<int:pk>/', view_admin.Eliminar_categoria.as_view(),
     name='admin_eliminar_categorias'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

src/cart/urls.py
from os import name
from django.urls import path
from . import views

app_name =  'cart'

urlpatterns = [
    path('', views.CartView.as_view(), name='summary'),
    path('shop/', views.ProductListView.as_view(), name='product-list'),
    path('shop/<slug>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('increase-quantity/<pk>/', 
        views.IncreaseQuantityView.as_view(), name='increase-quantity'),
    path('decrease-quantity/<pk>/', 
        views.DecreaseQuantityView.as_view(), name='decrease-quantity'),
    path('remove-from-cart/<pk>/', 
        views.RemoveFromCartView.as_view(), name='remove-from-cart'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('payment/', views.PaymentView.as_view(), name='payment'),
    path('thank-you/', views.ThankYouView.as_view(), name='thank-you'),
    path('confirm-order/', views.ConfirmOrderView.as_view(), name='confirm-order'),
    path('orders/<pk>/', views.OrderDetailView.as_view(), name='order-detail'),
]

src/templates/base.html
{% load static %}
{% load cart_template_tags %}


<!DOCTYPE html>
<html lang="en">
<head>
    <title>Jardines, Paisajes y Bosques {% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock extra_head %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'icons/apple-icon-57x57.png' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'icons/apple-icon-60x60.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'icons/apple-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'icons/apple-icon-76x76.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'icons/apple-icon-114x114.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'icons/apple-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'icons/apple-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'icons/apple-icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'icons/apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192" href="{% static 'icons/android-icon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'icons/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'icons/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'icons/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'icons/manifest.json' %}">
    <link href="https://unpkg.com/ionicons@4.5.10-0/dist/css/ionicons.min.css" rel="stylesheet">

    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{% static 'icons/ms-icon-144x144.png' %}">
    <meta name="theme-color" content="#ffffff">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Mukta:300,400,700">
    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/footer.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/aos.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css"
          integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous"/>
</head>

<body>

<div class="site-wrap">
    <header class="site-navbar" role="banner">
        <div class="site-navbar-top">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-6 col-md-8 mb-3 mb-md-0 col-md-4 order-1 order-md-2">
                        <div>
                            <a href="{% url 'home' %}">
                                <img class="img-fluid" src="{% static 'images/InicioLogo.png' %}" style="max-width: 220px;"/>
                            </a>
                        </div>
                    </div>

                    <div class="col-6 col-md-4 order-3 order-md-3 text-right">
                        <div class="site-top-icons">
                            <ul>
                                <li>
                                    {% if request.user.is_authenticated %}
                                        <a href="{% url 'profile' %}"><span><i class="fas fa-user"> Perfil</i></span></a>
                                    {% else %}
                                        <a href="{% url 'account_login' %}"><span><i
                                                class="fas fa-sign-in-alt"> Iniciar Sesión</i></span></a>
                                    {% endif %}
                                </li>
                                <li>
                                    <a href="{% url 'cart:summary'%}" class="site-cart">
                                        <span><i class="fas fa-shopping-cart"> Carrito</i></span>
                                        <span class="count">{{ request|cart_item_count }}</span>
                                    
                                    </a>
                                </li>
                                <li class="d-inline-block d-md-none ml-md-0">
                                    <a href="#" class="site-menu-toggle js-menu-toggle">
                                        <span><i class="fas fa-bars"></i></span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        {% include 'navbar.html' %}
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    <span class="alert-inner--icon"><i class="ni ni-like-2"></i></span>
                    <span class="alert-inner--text">{{ message }}</span>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endfor %}
        {% endif %}

    </header>

    {% block content %}
    {% endblock content %}

    {% include 'footer.html' %}

</div>

{% include 'scripts.html' %}

{% block scripts %}
{% endblock scripts %}

</body>
</html>

src/templates/contact.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="bg-light py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a href="{% url 'home' %}">Inicio</a>
                <span class="mx-2 mb-0">/</span>
                <strong class="text-block">Contactos</strong>
            </div>
        </div>
    </div>
</div>

<div class="site-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-7">
                <h2 class="h3 mb-3 text-black">Ponerse en contacto</h2>
            </div>

            <div class="col-md-7">
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input type="submit" class="btn btn-success btn-lg btn-block" value="Enviar Mensaje"/>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

src/templates/footer.html
{% load static %}

<footer class="col-lg-12 text-center p-4 derechos" style="background-color: #33383c; color: #FFF;" >
 <div class="container">
   <div class="row">
            <div class="col-md-4 col-sm-12 col-xs-12">
                <br><br>
                <div>
                    <a href="{% url 'home' %}">
                        <img class="img-fluid" src="{% static 'images/Logo.png' %}" style="max-width: 200px;"/>
                    </a>
                </div>
            </div>
            
            <div class="col-md-4 col-sm-6 col-s-12">
                <ul class="menu">
                     <span>Menú</span>    
                     <li >
                        <a href="/">INICIO</a>
                      </li>
                      <li>
                         <a href="{% url 'cart:product-list' %}">TIENDA</a>
                      </li>
                      <li>
                        <a href="{% url 'nosotros' %}">NOSOTROS</a>
                      </li>
                      <li>
                         <a href="{% url 'contact' %}">CONTACTOS</a>
                      </li>
                 </ul>
            </div>
       
            <div class="col-md-4 col-sm-6 col-s-12">
              <ul class="address">
                <span>Contáctenos</span>       
                <li>
                   <i class="icon ion-md-home"></i>
                   Mz A. A1 Lote. 5 A.v. Los Industriales-Cieneguilla
                </li>
                <li>
                   <i class="icon ion-md-call"></i>
                   01-4790278 Perú-Lima 
                </li> 
                <li>
                   <i class="icon ion-md-mail"></i>
                   jardines_paisajes_bosques@hotmail.com
                </li> 
               </ul>
            </div>
        </div> 
    </div >
</footer>
<div class="col-lg-12 text-center p-4 derechos" style="background-color: #33383c; color: #FFF;">
    <p>
        Copyright &copy;
        <script>document.write(new Date().getFullYear());</script>
        Jardines, Paisajes y Bosques</i>
    </p>
</div>

src/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static 'images/carrusel1.jpg' %}" class="d-block w-100"  height="700px" width="600px">
    </div>
    <div class="carousel-item">
      <img src="{% static 'images/carrusel2.jpg' %}" class="d-block w-100"  height="700px" width="600px">
    </div>
    <div class="carousel-item">
      <img src="{% static 'images/carrusel3.jpg' %}" class="d-block w-100"  height="700px" width="600px">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<!-- START THE FEATURETTES -->
<div class="container">
<hr class="featurette-divider">

<div class="row featurette">
  <div class="col-md-7 ">
    <h2 class="featurette-heading"><span class="text-black ">MANTENIMIENTO</span></h2>
    <p class="lead">Ofrecemos nuestro servicio de Mantenimiento de plantas tanto en oficinas,
        casas, departamentos y jardines en general. Su paisaje puede cambiar fácilmente con las
        estaciones y los años, deje sus plantas en nuestras manos que las cuidaremos para que
        siempre estén en su mejor momento.</p>
    <p><a class="btn btn-success" href="{% url 'contact' %}">Contáctenos &raquo;</a></p>
  </div>
  <div class="col-md-5 ">
    <img class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" src="{% static 'images/servicios.png' %}" >
  </div>
</div>

<hr class="featurette-divider">

<div class="row featurette">
  <div class="col-md-7 order-md-2">
    <h2 class="featurette-heading"><span class="text-black">DISEÑO DE JARDINES</span></h2>
    <p class="lead">Nuestros profesionales del diseño del paisaje están capacitados para ayudarle a crear un ambiente único, relajante y agradable para su hogar.</p>
    <p><a class="btn btn-success" href="{% url 'contact' %}">Contáctenos &raquo;</a></p>
  </div>
  <div class="col-md-5 order-md-1">
    <img class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" src="{% static 'images/servicios1.jpg' %}"  >
  </div>
</div>

<hr class="featurette-divider">
</div>

<!-- /END THE FEATURETTES -->

{% endblock content %}

src/templates/navbar.html
<nav class="site-navigation text-right text-md-center" role="navigation">
    <div class="container">
        <ul class="site-menu js-clone-nav d-none d-md-block" style="padding: 0;">
            <li><a href="/">Inicio</a></li>
            <li><a href="{% url 'cart:product-list' %}">Tienda</a></li>
            <li><a href="{% url 'nosotros' %}">Nosotros</a></li>
            <li><a href="{% url 'contact' %}">Contactos</a></li>
            {% if request.user.is_staff %}
                <li><a href="{% url 'admin' %}">Admin</a></li>
            {% endif %}
        </ul>
    </div>
</nav>

src/templates/nosotros.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<!-- START THE FEATURETTES -->
<div class="container">
<hr class="featurette-divider">

<div class="row featurette">
  <div class="col-md-7 ">
    <h2 class="featurette-heading"><span class="text-black ">¿Quiénes somos?</span></h2>
    <p class="lead">Somos una empresa fundada el 22 de enero del 2009 bajo la dirección del Sr. 
    Rafael Poma Cordova y el Sr. Luis Allcca Alhuay con la finalidad de brindar la mejor expericiencia
     y resultado en los servicios que nuestros clientes solicitan.</p>
  </div>
  <div class="col-md-5 ">
    <img class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" src="{% static 'images/nosotros.jpeg' %}" >
  </div>
</div>

<hr class="featurette-divider">

<div class="row featurette">
  <div class="col-md-7 order-md-2">
    <h2 class="featurette-heading"><span class="text-black">¿Cuál es nuestra visión?</span></h2>
    <p class="lead">Incrementar la competitividad en el mercado, obteniendo así una posición reconocida
     dentro del sector en cuestión y, de esta manera, aumentar el público objetivo.</p>
    <h2 class="featurette-heading"><span class="text-black">¿Cuál es nuestra misión?</span></h2>
    <p class="lead">Brindar un buen servicio en las áreas verdes.</p>
  </div>
  <div class="col-md-5 order-md-1">
    <img class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" src="{% static 'images/nosotros1.jpeg' %}"  >
  </div>
</div>

<hr class="featurette-divider">
</div>

<!-- /END THE FEATURETTES -->

{% endblock content %}

src/templates/order.html
{% extends "base.html" %}

{% block content %}
<div class="site-sectino">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-m-12">
                <a href="{% url 'profile' %}">Volver al perfil</a>
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">
                            Pedido: #{{ order.reference_number }}
                        </h5>
                        <h6 class="card-subtitle mb-2 text-muted">Pedido en: {{ order.ordered_date }}</h6>
                    </div>
                    <hr />
                    
                    <div class="site-blocks-table">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Producto</th>
                                    <th>Total</th>
                                    
                                </tr>
                            </thead>
                            <tbody>
                                {% for item in order.items.all %}
                                <tr>
                                    <td>{{ item.size.name }}, {{ item.colour.name }} of {{ item.product.title }} x {{ item.quantity }}</td>
                                    <td>${{ item.get_total_item_price }}</td>
                                </tr>
                                
                                {% endfor %}

                                <tr>
                                    <td>Subtotal</td>
                                    <td>${{ order.get_subtotal }}</td>
                                </tr>
                                <tr>
                                    <td>Total</td>
                                    <td>${{order.get_total}}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

src/templates/profile.html
{% extends "base.html" %}

{% block content %}
<div class="site-sectino">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-m-12">
                <h2 class="text-black">Tu Cuenta</h2>
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ request.user.email }}</h5>
                        <a href="{% url 'account_logout' %}"><small class="float-right">Cerrar Sesión</small></a>
                    </div>
                    <hr />
                    <h5 class="card-title">Tus órdenes</h5>
                    <div class="site-blocks-table">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>N° de Referencia</th>
                                    <th>Fecha</th>
                                    <th>Monto</th>
                                    <th>Estado del Pago</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for order in orders %}
                                <tr>
                                    <a href="{% url 'cart:order-detail' order.pk %}"><td>#{{ order.reference_number }}</td></a>
                                    <td>{{ order.ordered_date }}</td>
                                    <td>$ {{ order.get_total }}</td>
                                    <td>{% if order.ordered %}Pagado{% else %}No Pagado{% endif %}</td>
                                </tr>
                                {% empty %}
                                <tr>
                                    <td colspan="4">No ha realizado ninguna compra.</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<br> <br>
{% endblock content %}

src/templates/scripts.html
{% load static %}

<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/jquery-ui.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/aos.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
 <script src="https://account.snatchbot.me/script.js"></script><script>window.sntchChat.Init(184390)</script> 