src/app/urls.py
from os import name
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

from core import views

from admin import view_admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', views.HomeView.as_view(), name='home'),
    path('contact/',views.ContactView.as_view(), name='contact'),
    path('nosotros/',views.NosotrosView.as_view(), name='nosotros'),
    path('cart/', include('cart.urls', namespace='cart')),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    
    path('adminprincipal/', view_admin.adminprincipal, name='admin'),
    path('admin_ver_productos/', view_admin.Admin_ver_productos.as_view(), 
         name='admin_ver_productos'),
    path('admin_añadir_productos/', view_admin.Admin_Agregar_productos.as_view(), 
         name='admin_agregar_productos'),
    path('admin_actualizar_productos/<int:pk>/', view_admin.Actualizar_producto.as_view(),
         name='admin_actualizar_productos'),
    path('admin_eliminar_productos/<int:pk>/', view_admin.Eliminar_producto.as_view(),
         name='admin_eliminar_productos'),
    path('admin_ver_proveedores/', view_admin.Admin_ver_proveedores.as_view(), 
        name='admin_ver_proovedores'),
    path('admin_añadir_proveedores/', view_admin.Admin_Agregar_proveedores.as_view(), 
        name='admin_agregar_proovedores'),
    path('admin_actualizar_proovedores/<int:pk>/', view_admin.Actualizar_proveedores.as_view(),
         name='admin_actualizar_proovedores'),
    path('admin_ver_ventas/', view_admin.Admin_ver_ordenes, 
         name='admin_ver_ventas'),
    path('admin_ver_pagos/', view_admin.Admin_ver_pagos.as_view(), 
         name='admin_ver_pagos'),
    path('admin_ver_usuarios/', view_admin.Admin_ver_usuarios, 
         name='admin_ver_usuarios'),
    path('admin_registrar_usuarios/', view_admin.administrador_signup_view , 
         name='admin_registrar_usuarios'),
    path('admin_actualizar_administradores/<int:pk>', view_admin.admin_acutalizar_administradores,
         name='admin_actualizar_administradores'),
     path('admin_ver_categorias/', view_admin.Admin_ver_categorias.as_view(), name='admin_ver_categorias'),
     path('admin_añadir_categorias/', view_admin.Admin_Agregar_categorias.as_view(), name='admin_agregar_categorias'),
     path('admin_actualizar_categorias/<int:pk>/', view_admin.Actualizar_categoria.as_view(),
     name='admin_actualizar_categorias'),
     path('admin_eliminar_categorias/<int:pk>/', view_admin.Eliminar_categoria.as_view(),
     name='admin_eliminar_categorias'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

src/cart/urls.py
from os import name
from django.urls import path
from . import views

app_name =  'cart'

urlpatterns = [
    path('', views.CartView.as_view(), name='summary'),
    path('shop/', views.ProductListView.as_view(), name='product-list'),
    path('shop/<slug>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('increase-quantity/<pk>/', 
        views.IncreaseQuantityView.as_view(), name='increase-quantity'),
    path('decrease-quantity/<pk>/', 
        views.DecreaseQuantityView.as_view(), name='decrease-quantity'),
    path('remove-from-cart/<pk>/', 
        views.RemoveFromCartView.as_view(), name='remove-from-cart'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('payment/', views.PaymentView.as_view(), name='payment'),
    path('thank-you/', views.ThankYouView.as_view(), name='thank-you'),
    path('confirm-order/', views.ConfirmOrderView.as_view(), name='confirm-order'),
    path('orders/<pk>/', views.OrderDetailView.as_view(), name='order-detail'),
]

src/cart/forms.py
from django import forms
from .models import OrderItem, Product, Address, Proveedores, Administrador, Category
from django.contrib.auth import get_user_model

from django.forms import ModelForm

User = get_user_model()


# PARA AGREGAR AL CARRITO
class AddToCartForm(forms.ModelForm):
    quantity = forms.IntegerField(min_value=1, label='Cantidad',)

    class Meta:
        model = OrderItem
        fields = ['quantity']

    def __init__(self, *args, **kwargs):
        product_id = kwargs.pop('product_id')
        product = Product.objects.get(id=product_id)
        super().__init__(*args, **kwargs)

# CREANDO LOS CAMPOS PARA EL ENVÍO DEL PRODUCTO
class AddressFrom(forms.Form):
    shipping_address_line_1 = forms.CharField(required=False,
        label='Dirección 1',  widget=forms.TextInput(attrs={
        'placeholder': "Ingrese su primera dirección de envio",

    },)
                                              )
    shipping_address_line_2 = forms.CharField(required=False, label='Dirección 2',  widget=forms.TextInput(attrs={
        'placeholder': "Ingrese su segunda dirección de envio",

    }))
    shipping_zip_code = forms.CharField(required=False, label='Codigo Postal' ,  widget=forms.TextInput(attrs={
        'placeholder': "Ingrese su Codigo postal",

    }))
    shipping_departament = forms.CharField(required=False,label="Departamento", max_length=7, disabled=True, widget=forms.TextInput(attrs={
        'placeholder': "Lima",

    }))

    shipping_city = forms.CharField(required=False, label='Ciudad',  widget=forms.TextInput(attrs={
        'placeholder': "Ingrese su ciudad de procedencia",

    }))



    selected_shipping_address = forms.ModelChoiceField(
        Address.objects.none(), required=False,label='Direcciones Guardadas'
    )

    def __init__(self, *args, **kwargs):
        user_id = kwargs.pop('user_id')
        super().__init__(*args, **kwargs)

        if not user_id is None:
            user = User.objects.get(id=user_id)

            shipping_address_qs = Address.objects.filter(
                user=user,
                address_type='S'
            )

            self.fields['selected_shipping_address'].queryset = shipping_address_qs

    def clean(self):
        data = self.cleaned_data

        selected_shipping_address = data.get('selected_shipping_address', None)
        if selected_shipping_address is None:
            if not data.get('shipping_address_line_1', None):
                self.add_error("shipping_address_line_1", "Please fill in this field")
            if not data.get('shipping_address_line_2', None):
                self.add_error("shipping_address_line_2", "Please fill in this field")
            if not data.get('shipping_zip_code', None):
                self.add_error("shipping_zip_code", "Please fill in this field")
            if not data.get('shipping_city', None):
                self.add_error("shipping_city", "Please fill in this field")


class ProductoForm(ModelForm):
    class Meta:
        model = Product
        fields = "__all__"
        help_texts = {
            'active': 'Group to which this message belongs to',
        }
        labels = {
            'active': 'Group to which this message belongs to',
        }


class ProveedorForm(ModelForm):
    class Meta:
        model = Proveedores
        fields = "__all__"


class CustomerUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'password','email', 'is_staff']
        widgets = {
            'password': forms.PasswordInput()
        }


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Administrador
        fields = ['dirreccion']


class CategoriaForm(ModelForm):
   class Meta:
       model = Category
       fields = "__all__"
       help_texts = {
           'name': 'Por favor ingrese una categoria en texto',

       }
       labels = {
           'name': 'Categoria',

       }

src/cart/views.py
import json
from django.http import JsonResponse
from django.views import generic
from django.db.models import Q
from .utils import get_or_set_order_session
from .models import Address, OrderItem, Product, Payment, Order, Category
from .forms import AddToCartForm, AddressFrom
from django.shortcuts import get_object_or_404, redirect, reverse
from django.contrib import messages
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone

class ProductListView(generic.ListView):
    template_name='cart/product_list.html'
    paginate_by = 6

    def get_queryset(self):
        qs = Product.objects.all()
        category = self.request.GET.get('category', None)
        if category:
            qs = qs.filter(Q(primary_category__name=category) |
                           Q(secondary_categories__name=category))
        return qs

    def get_context_data(self, **kwargs):
        context = super(ProductListView, self).get_context_data(**kwargs)
        context.update({
            "categories": Category.objects.all()
        })
        return context


class ProductDetailView(generic.FormView):
    
    template_name = 'cart/product_detail.html'
    form_class = AddToCartForm
    
    def get_object(self):
        return get_object_or_404(Product, slug=self.kwargs["slug"])

    def get_success_url(self):
        return reverse("cart:summary")

    def get_form_kwargs(self):
        kwargs = super(ProductDetailView, self).get_form_kwargs()
        kwargs["product_id"] = self.get_object().id
        return kwargs

    def form_valid(self, form):
        order = get_or_set_order_session(self.request)
        product = self.get_object()

        item_filter = order.items.filter(
            product=product,

        )

        if item_filter.exists():
            item = item_filter.first()
            item.quantity += int(form.cleaned_data['quantity'])
            product.stock -= int(form.cleaned_data['quantity'])
            product.save()
            item.save()

        else:
            new_item = form.save(commit=False)
            new_item.product = product
            product.stock -= int(form.cleaned_data['quantity'])
            product.save()
            new_item.order = order
            new_item.save()


        return super(ProductDetailView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        context ['product'] = self.get_object()
        return context    


class CartView(generic.TemplateView):
    template_name = 'cart/cart.html'


    def get_context_data(self, **kwargs):
        context = super(CartView,self).get_context_data(**kwargs)
        context["order"] = get_or_set_order_session(self.request)
        return context


class IncreaseQuantityView(generic.View):
    def get(self, request, *args, **kwargs):
        order_item = get_object_or_404(OrderItem, id=kwargs['pk'])
        order_item.quantity += 1
        order_item.save()
        return redirect("cart:summary")


class DecreaseQuantityView(generic.View):
    def get(self, request, *args, **kwargs):
        order_item = get_object_or_404(OrderItem, id=kwargs['pk'])

        if order_item.quantity <= 1:
            order_item.delete()
        else:
            order_item.quantity -= 1
            order_item.save()
        return redirect("cart:summary")


class RemoveFromCartView(generic.View):
    def get(self, request, *args, **kwargs):
        order_item = get_object_or_404(OrderItem, id=kwargs['pk'])
        order_item.delete()
        return redirect("cart:summary")

class CapturarCartView(generic.View):
    def get(self, request, *args, **kwargs):
        order_item = get_object_or_404(OrderItem, id=kwargs['pk'])
        order_item.delete()
        return redirect("cart:summary")

class CheckoutView(generic.FormView):
    template_name = 'cart/checkout.html'
    form_class = AddressFrom

    def get_success_url(self):
        return reverse("cart:payment")

    def form_valid(self, form):
        order = get_or_set_order_session(self.request)
        selected_shipping_address = form.cleaned_data.get('selected_shipping_address')

        if selected_shipping_address:
            order.shipping_address = selected_shipping_address
        else:
            address = Address.objects.create(
                address_type = 'S',
                user = self.request.user,
                address_line_1=form.cleaned_data['shipping_address_line_1'],
                address_line_2=form.cleaned_data['shipping_address_line_2'],

                zip_code=form.cleaned_data['shipping_zip_code'],
                city=form.cleaned_data['shipping_city'],

            )
            order.shipping_address = address
        order.save()


        messages.info(
            self.request, "Has llenado todo correctamente")
        return super(CheckoutView, self).form_valid(form)

    def get_form_kwargs(self):
        kwargs = super(CheckoutView, self).get_form_kwargs()
        kwargs["user_id"] = self.request.user.id
        return kwargs

    def get_context_data(self, **kwargs):
        context = super(CheckoutView, self).get_context_data(**kwargs)
        context ['order'] = get_or_set_order_session(self.request)
        return context


class PaymentView(generic.TemplateView):
    template_name = 'cart/payment.html'

    def get_context_data(self, **kwargs):
        context = super(PaymentView, self).get_context_data(**kwargs)
        context ['PAYPAL_CLIENT_ID'] = settings.PAYPAL_CLIENT_ID
        context ['order'] = get_or_set_order_session(self.request)
        context ['CALLBACK_URL'] = self.request.build_absolute_uri(reverse("cart:thank-you"))
        return context  

class ConfirmOrderView(generic.View):

    def post(self, request, *args, **kwargs):
        order = get_or_set_order_session(request)
        body = json.loads(request.body)
        payment = Payment.objects.create(
            order=order,
            succesful=True,
            raw_response = json.dumps(body),
            amount = float(body["purchase_units"][0]["amount"]["value"]),
            payment_method='Paypal'
        )
        order.ordered = True
        order.ordered_date = timezone.now()
        order.save()
        return JsonResponse({"data":"Success"})

class ThankYouView(generic.TemplateView):
    template_name = 'cart/thanks.html'

class OrderDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = 'order.html'
    queryset = Order.objects.all()
    context_object_name = 'order'

src/templates/cart/cart.html
{% extends "base.html" %}

{% block content %}

<div class="bg-light py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a href="{% url 'home' %}">Inicio</a>
                <span class="mx-2 mb-0">/</span>
                <strong class="text-block">Carrito</strong>
            </div>
        </div>
    </div>
</div>

<div class="site-section">
    <div class="container">
        <div class="row mb-5">

            <div class="col-md-12">
                <div class="site-blocks-table">
                    <table>
                        <thead>
                            <tr>
                                <th>Imagen</th>
                                <th>Producto</th>
                                <th>Precio (soles)</th>
                                <th>Cantidad</th>
                                <th>Total (dólares)</th>
                                <th>Accion</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in order.items.all %}
                            <tr>
                                <td class="product-thumbnail">
                                    <img src="{{ item.product.image.url }}" class="img-fluid">
                                </td>
                                <td class="product-name">
                                    <h2 class="h5 text-black">{{ item.product.title }}</h2>
                                    <small> {{ item.product.slug }}</small>
                                </td>
                                <td>S/. {{ item.product.get_price }}</td>
                                <td>
                                    <div class="input-group mb-3" style="max-width: 120px;">
                                        <div class="input-group-pretend">
                                            <a href="{% url 'cart:decrease-quantity' item.id %}" class="btn btn-outline-success">
                                                &minus;
                                            </a>
                                        </div>
                                        <input type="text" class="form-control text-center" 
                                        value="{{item.quantity}}" disabled>
                                        <div class="input-group-pretend">
                                            <a href="{% url 'cart:increase-quantity' item.id %}" class="btn btn-outline-success">
                                                &plus;
                                            </a>
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    ${{ item.get_total_item_price }}
                                </td>
                                <td>
                                    <a href="{% url 'cart:remove-from-cart' item.id %}" class="btn btn-danger btn-sm">x</a>
                                </td>
                            </tr>
                            {% empty %}
                            <tr>
                                <td colspan="6">
                                    No hay productos en el carrito. <a href="{% url 'cart:product-list' %}">Continuar Comprando</a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>


            
            
        </div>

        {% if order.items.count > 0 %}
            <div class="row">
                <div class="col-md-6">
                    <div class="row mb-5">
                        <div class="col-md-12">
                            <a class="btn btn-outline-primary btn-sm btn-block" 
                            href="{% url 'cart:product-list' %}">Continuar Comprando</a>
                        </div>
                    </div>
                </div>

                <div class="col-md-6 pl-5">
                    <div class="row justify-content-end">
                        <div class="col-md-12">
                            <div class="row">
                                <div class="col-md-12 text-right border-bottom mb-5">
                                    <h3 class="text-black h4 text-uppercase">Total del Carrito</h3>
                                </div>
                            </div>

                            <div class="row mb-3">
                                <div class="col-md-6">
                                    <span class="text-black">SubTotal</span>
                                </div>

                                <div class="col-md-6 text-right">
                                    <strong class="text-black">${{ order.get_subtotal }}</strong>
                                </div>
                            </div>

                            <div class="row mb-5">
                                <div class="col-md-6">
                                    <span class="text-black">Total</span>
                                </div>

                                <div class="col-md-6 text-right">
                                    <strong class="text-black">${{ order.get_total }}</strong>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <a href="{% url 'cart:checkout' %}" class="btn btn-warning btn-lg py-3 btn-block">
                                        Proceder a Pagar
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        {% endif %}

    </div>
</div>

{% endblock content %}

src/templates/cart/checkout.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="bg-light py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a href="{% url 'home' %}">Inicio</a>
                <span class="mx-2 mb-0">/</span>
                <a href="{% url 'cart:summary' %}">Carrito</a>
                 <span class="mx-2 mb-0">/</span>
                <strong class="text-block">Verificar</strong>
            </div>
        </div>
    </div>
</div>

<div class="site-section">
    <div class="container">
            {% if not request.user.is_authenticated %}
            <div class="row mb-5">
                <div class="col-md-12">
                    <div class="border p-4 rounded" role="alert">
                        Ya casi ha terminado con su pedido.
                        Para finalizar su pedido, por favor <a href="{% url 'account_login' %}">Inicie Sesión</a> or <a href="/accounts/signup/">Regístrese</a>
                    </div>

                    <div class="progress">
                        <div class="progress-bar" role="progressbar" style="width: 90%;" aria-label="90" aria-valuemin="0" aria-valuemax="100">
                            90% Completado
                        </div>
                    </div>
                </div>
            </div>
            {% else %}

            <form method="POST">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-6 mb-md-0">
                        <h2 class="h3 mb-3 text-black text-center">Detalles de facturación</h2>
                        <hr />
                        <div class="p-2 p-lg-2">
                            {{ form|crispy }}
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-success btn-lg py-3 btn-block">
                                Proceder al pago
                            </button>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="row mb-5">
                            <div class="col-md-12">
                                <h2 class="h3 mb-3 text-black text-center">Tu orden</h2>
                                <hr>
                                <div class="p-3 p-lg-5">
                                    <table class="table site-block-order-table mb-5">
                                        <thead>
                                            <th>Producto</th>
                                            <th>Total</th>
                                        </thead>
                                        <tbody>
                                            {% for item in order.items.all %}
                                            <tr>
                                                <td>
                                                    {{ item.size.name }}, {{ item.colour.name}}, {{ item.product.title}}
                                                    <strong class="mx-2">x</strong> {{ item.quantity }}
                                                </td>
                                                <td>
                                                    ${{ item.get_total_item_price }}
                                                </td>
                                            </tr>
                                            {% endfor %}
                                            <tr>
                                                <td><strong class="text-black font-weight-bold">Subtotal</strong></td>
                                                <td>${{ order.get_subtotal }}</td>
                                            </tr>
                                            <tr>
                                                <td><strong>Total del pedido</strong></td>
                                                <td><strong class="text-black font-weight-bold">${{ order.get_total }}</strong></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>

            {% endif %}
    </div>
</div>
{% endblock content %}

src/templates/cart/payment.html
{% extends "base.html" %}

{% block content %}

<style>
.lds-ring {
  display: inline-block;
  position: relative;
  width: 80px;
  height: 80px;
}
.lds-ring div {
  box-sizing: border-box;
  display: block;
  position: absolute;
  width: 64px;
  height: 64px;
  margin: 8px;
  border: 8px solid rgb(155, 81, 81);
  border-radius: 50%;
  animation: lds-ring 1.2s cubic-bezier(0.5, 0, 0.5, 1) infinite;
  border-color: rgb(155, 81, 81) transparent transparent transparent;
}
.lds-ring div:nth-child(1) {
  animation-delay: -0.45s;
}
.lds-ring div:nth-child(2) {
  animation-delay: -0.3s;
}
.lds-ring div:nth-child(3) {
  animation-delay: -0.15s;
}
@keyframes lds-ring {
  0% {
    transform: rotate(0deg);
  }
  100% {
    transform: rotate(360deg);
  }
}

</style>


<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">

            <div class="alert alert-success" role="alert" id="alertSuccess" style="display: none;">
                Tu pago fue exitoso.
            </div>

            <div class="alert alert-danger" role="alert" id="alertFailure" style="display: none;">
                Tu pago falló. Inténtalo de nuevo.
            </div>


            <div class="text-center py-3">
                <div id="loader" class="lds-ring" style="margin:auto; display:none;">
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                </div>
            </div>
            

            <div id='paymentInfo'>
                <p>Total del pedido: ${{ order.get_total }}</p>
                <h4>Seleccione una forma de pago</h4>
                <div id="paypal-button-container"></div>
            </div>

        </div>
        
    </div>
</div>


{% endblock content %}


{% block scripts %}
    <script src="https://www.paypal.com/sdk/js?client-id={{ PAYPAL_CLIENT_ID }}"></script>

    <script>

        const loader = document.getElementById('loader');
        const paymentInfo = document.getElementById('paymentInfo')

        function toggleLoader(on){
          loader.style.display = on === true ? "block" : "none";
          paymentInfo.style.display = on === true ? "none" : "block";
        }

        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        const csrftoken = getCookie('csrftoken');

        function sendOrderConfirmed(details){
            return fetch("{% url 'cart:confirm-order' %}", {
               method: "POST",
               body: JSON.stringify(details),
               headers: {
                 "Content-Type": "application/json",
                 "X-CSRFToken": csrftoken
               }
            })
        }

        paypal.Buttons({
          createOrder: function(data, actions) {
            return actions.order.create({
                purchase_units: [{
                  amount: {
                    value: '{{ order.get_total }}'
                  }
                }]
            });
          },
          onApprove: function(data, actions) {
            toggleLoader(true);
            return actions.order.capture().then(function(details) {
                sendOrderConfirmed(details).then(res => {
                  toggleLoader(false)

                  const alertSuccess = document.getElementById('alertSuccess');
                  alertSuccess.style.display = 'block';
                  
                  setTimeout(function() {
                      window.location.replace("{{ CALLBACK_URL }}")
                  }, 3000);
                })
            })
                .catch(err => {
                  const alertFailure = document.getElementById('alertFailure');
                  alertFailure.style.display = 'block';
                })
                .finally(() => toggleLoader(false));
          }
        }).render('#paypal-button-container');
    </script>
{% endblock scripts %}

src/templates/cart/product_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="bg-light py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a href="{% url 'home' %}">Inicio</a>
                <span class="mx-2 mb-0">/</span>
                <strong class="text-block">{{ product.title }}</strong>
            </div>
        </div>
    </div>
</div>

<div class="site-section">
    <div class="container">
        <div class="row mb-5">

            <div class="col-md-6">
                <a><img  src="{{ product.image.url }}" class="img-fluid"></a>
            </div>

                <div class="col-md-6 mb-4" data-aos='fade-up'>

                    <h2 class="text-black">{{ product.title }}</h2>
                    <p>{{ product.description }}</p>
                    <p>Stock disponible: {{ product.stock }}</p>
                    <p>Precio: S/. {{ product.get_price }}</p>
                    {% if product.in_stock %}
                    <form method="POST">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type='submit' class="btn btn-sm btn-primary buy-now">Añadir al carrito</button>
                    </form>

                    {% else %}
                    <p>Este artículo no está en inventario</p>
                    {% endif %}
                </div>
            
            
        </div>
    </div>
</div>



{% endblock content %}

src/templates/cart/thanks.html
{% extends "base.html" %}

{% block content %}

<h2>Gracias por comprar en Jardines, Paisajes y Bosques</h2>

{% endblock content %}